version: '3.8'
services:
  # Spring Boot API Service
  blackjack-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Connecting to MySQL (R2DBC)
      SPRING_R2DBC_URL: r2dbc:mysql://mysql-db:3306/blackjack_db
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: password
      # Connecting to MongoDB
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/blackjack_game_db
    depends_on:
      - mysql-db
      - mongo-db

  # MySQL Service
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: blackjack_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  # MongoDB Service
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"