version: '3.8'
services:
  # Spring Boot API Service
  blackjack-api:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      # Connecting to MySQL (R2DBC)
      SPRING_R2DBC_URL: r2dbc:mysql://mysql-db:3306/blackjack_db
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: password
      # Connecting to MongoDB
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/blackjack_game_db

    depends_on:
      mysql-db:
        condition: service_healthy
      mongo-db:
        condition: service_started

  # MySQL Service
  mysql-db:
    image: mysql:8.0
    container_name: blackjack-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blackjack_db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Service
  mongo-db:
    image: mongo:latest
    container_name: blackjack-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: