spring:
  application:
    name: blackjack-webflux
  data:
    mongodb:
      uri: mongodb://mongo:27017/blackjackdb
  r2dbc:
    url: r2dbc:mysql://mysql:3306/blackjackdb
    username: root
    password: password

server:
  port: 8080

logging:
  level:
    root: INFO
